
export const districtOptions = [
    { label: "Bau", value: "Bau" },
    { label: "Belaga", value: "Belaga" },
    { label: "Betong", value: "Betong" },
    { label: "Bintulu", value: "Bintulu" },
    { label: "Dalat", value: "Dalat" },
    { label: "Daro", value: "Daro" },
    { label: "Julau", value: "Julau" },
    { label: "Kabong", value: "Kabong" },
    { label: "Kanowit", value: "Kanowit" },
    { label: "Kapit", value: "Kapit" },
    { label: "Kuching", value: "Kuching" },
    { label: "Limbang", value: "Limbang" },
    { label: "Miri", value: "Miri" },
    { label: "Mukah", value: "Mukah" },
    { label: "Pakan", value: "Pakan" },
    { label: "Pitas", value: "Pitas" },
    { label: "Samarahan", value: "Samarahan" },
    { label: "Sarikei", value: "Sarikei" },
    { label: "Serian", value: "Serian" },
    { label: "Simunjan", value: "Simunjan" },
    { label: "Song", value: "Song" },
    { label: "Sri Aman", value: "Sri Aman" },
    { label: "Subis", value: "Subis" },
    { label: "Tatau", value: "Tatau" },
  ];
  
  export const stateOptions = [
    { label: "Johor", value: "Johor" },
    { label: "Kedah", value: "Kedah" },
    { label: "Kelantan", value: "Kelantan" },
    { label: "Kuala Lumpur", value: "Kuala Lumpur" },
    { label: "Labuan", value: "Labuan" },
    { label: "Melaka", value: "Melaka" },
    { label: "Negeri Sembilan", value: "Negeri Sembilan" },
    { label: "Pahang", value: "Pahang" },
    { label: "Perak", value: "Perak" },
    { label: "Perlis", value: "Perlis" },
    { label: "Pulau Pinang", value: "Pulau Pinang" },
    { label: "Sabah", value: "Sabah" },
    { label: "Sarawak", value: "Sarawak" },
    { label: "Selangor", value: "Selangor" },
    { label: "Terengganu", value: "Terengganu" },
  ];
  
